require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/books_uploads", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # BooksUpload. As you add validations to BooksUpload, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      BooksUpload.create! valid_attributes
      get books_uploads_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      books_upload = BooksUpload.create! valid_attributes
      get books_upload_url(books_upload)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_books_upload_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      books_upload = BooksUpload.create! valid_attributes
      get edit_books_upload_url(books_upload)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new BooksUpload" do
        expect {
          post books_uploads_url, params: { books_upload: valid_attributes }
        }.to change(BooksUpload, :count).by(1)
      end

      it "redirects to the created books_upload" do
        post books_uploads_url, params: { books_upload: valid_attributes }
        expect(response).to redirect_to(books_upload_url(BooksUpload.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new BooksUpload" do
        expect {
          post books_uploads_url, params: { books_upload: invalid_attributes }
        }.to change(BooksUpload, :count).by(0)
      end

    
      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post books_uploads_url, params: { books_upload: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested books_upload" do
        books_upload = BooksUpload.create! valid_attributes
        patch books_upload_url(books_upload), params: { books_upload: new_attributes }
        books_upload.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the books_upload" do
        books_upload = BooksUpload.create! valid_attributes
        patch books_upload_url(books_upload), params: { books_upload: new_attributes }
        books_upload.reload
        expect(response).to redirect_to(books_upload_url(books_upload))
      end
    end

    context "with invalid parameters" do
    
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        books_upload = BooksUpload.create! valid_attributes
        patch books_upload_url(books_upload), params: { books_upload: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested books_upload" do
      books_upload = BooksUpload.create! valid_attributes
      expect {
        delete books_upload_url(books_upload)
      }.to change(BooksUpload, :count).by(-1)
    end

    it "redirects to the books_uploads list" do
      books_upload = BooksUpload.create! valid_attributes
      delete books_upload_url(books_upload)
      expect(response).to redirect_to(books_uploads_url)
    end
  end
end
